version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - symfony
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
  web:
    image: nginx
    container_name: symfony_web
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - symfony
  db:
    image: postgres:16
    container_name: symfony_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - symfony
volumes:
  db-data:
networks:
  symfony:
    driver: bridge